server:
  port: 2525
  servlet:
    context-path: /solv

gotech:
  base_url: localhost:2525

controller:
  path: "com.solv.inventory.controller"

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #to resolve error related to swagger
  h2:
    console:
      enabled: true      # Enables the H2 console for logging
      path: /h2-console  # URL path to access the H2 console

  datasource:
    url: jdbc:h2:mem:testdb   # In-memory database
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    hibernate.ddl-auto: update
    show-sql: true